services:
  asr:
    build: .
    image: start-fm-asr
    container_name: start-fm-asr
    ports: ["8081:8081"]
    env_file: [.env]
    volumes:
      - ./gcp-key.json:/app/gcp-key.json:ro   # 鍵はイメージに含めない
      - ./:/app                               # ホットリロード用（開発）
    environment:
      WATCHFILES_FORCE_POLLING: "1"
    command: >
      uvicorn src.app.main:app
      --host 0.0.0.0 --port 8081
      --reload --reload-dir /app
